### ISSUE TITLE
All awscurl command fails after latest release

### ISSUE THREAD

**Issue by LuciCondescu** [okigan/awscurl#140]
It looks like the latest version doesn't work anymore when it's installed using pip.
`pip install awscurl`
The output of the install command is:
` Collecting awscurl
15:40:56  Requirement already satisfied: configargparse in /usr/local/lib/python2.7/dist-packages (from awscurl) (1.5.3)
15:40:56  Requirement already satisfied: configparser in /usr/lib/python2.7/dist-packages (from awscurl) (3.5.0b2)
15:40:56  Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from awscurl) (2.26.0)
15:40:56  Requirement already satisfied: urllib3[secure] in /usr/local/lib/python2.7/dist-packages (from awscurl) (1.26.7)
15:40:56  Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->awscurl) (2021.10.8)
15:40:56  Requirement already satisfied: idna<3,>=2.5; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from requests->awscurl) (2.10)
15:40:56  Requirement already satisfied: chardet<5,>=3.0.2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from requests->awscurl) (4.0.0)
15:40:56  Requirement already satisfied: pyOpenSSL>=0.14; extra == "secure" in /usr/local/lib/python2.7/dist-packages (from urllib3[secure]->awscurl) (21.0.0)
15:40:56  Requirement already satisfied: cryptography>=1.3.4; extra == "secure" in /usr/lib/python2.7/dist-packages (from urllib3[secure]->awscurl) (2.6.1)
15:40:56  Requirement already satisfied: ipaddress; python_version == "2.7" and extra == "secure" in /usr/lib/python2.7/dist-packages (from urllib3[secure]->awscurl) (1.0.17)
15:40:56  Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL>=0.14; extra == "secure"->urllib3[secure]->awscurl) (1.12.0)
15:40:56  Installing collected packages: awscurl
15:40:56  Successfully installed awscurl-0.26`

All the commands fail with:

`Traceback (most recent call last):
15:40:21    File "/usr/local/bin/awscurl", line 6, in <module>
15:40:21      from awscurl.__main__ import main
15:40:21    File "/usr/local/lib/python2.7/dist-packages/awscurl/__main__.py", line 6, in <module>
15:40:21      from .awscurl import main
15:40:21    File "/usr/local/lib/python2.7/dist-packages/awscurl/awscurl.py", line 19, in <module>
15:40:21      from urllib.parse import quote
15:40:21  ImportError: No module named parse`

Note that I have installed the package on Mac and I didn't run in the previous errors so everything works just fine if the package is installed with Homebrew.

Thanks

**Comment by LuciCondescu** [comment]
Thanks a lot, Igor. I finally understood what the problem actually was.
