### ISSUE TITLE
Doesn't handle URLs encoded with apostrophe correctly %27

### ISSUE THREAD

**Issue by TechieGary** [okigan/awscurl#15]
Called with URL that passes "Mike's 1043" encoded as Mike%27s%201043

Example URL
https://xxxxxxxxx.execute-api.us-west-2.amazonaws.com/prod/add?user=XX&data=Mike%27s%201043

'Response code: 400\n'
{"message": "Could not parse request body into json: Unrecognized character escape \'\'\' (code 39)\n at [Source: [B@742f0d86; line: 9, column: 34]"}
Traceback (most recent call last):
  File "/usr/local/bin/awscurl", line 11, in <module>
    sys.exit(main())
  File "/Users/Znn/Library/Python/2.7/lib/python/site-packages/awscurl/awscurl.py", line 276, in main
    args.security_token
  File "/Users/Znn/Library/Python/2.7/lib/python/site-packages/awscurl/awscurl.py", line 188, in make_request
    return send_request(uri, data, headers, method)
  File "/Users/Znn/Library/Python/2.7/lib/python/site-packages/awscurl/awscurl.py", line 218, in send_request
    r.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

**Comment by okigan** [comment]
@TechieGary include full command line that resulted in this issue

**Comment by okigan** [comment]
Time for clean up, @TechieGary do you have more info for the above or need to proceed to close this issue.

**Comment by okigan** [comment]
not enough info -- closing for now
