### ISSUE TITLE
v0.28 build failure with Homebrew

### ISSUE THREAD

**Issue by p-linnane** [okigan/awscurl#167]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v0.28 of awscurl, we are encountering a build failure.
```
 ==> /opt/homebrew/Cellar/awscurl/0.28/libexec/bin/pip install -v --no-deps --no-binary :all: --use-feature=no-binary-enable-wheel-cache --ignore-installed /private/tmp/awscurl-20230505-36434-1h15nfi/awscurl-0.28
  Using pip 23.0.1 from /opt/homebrew/Cellar/awscurl/0.28/libexec/lib/python3.11/site-packages/pip (python 3.11)
  Processing /private/tmp/awscurl-20230505-36434-1h15nfi/awscurl-0.28
    Preparing metadata (setup.py): started
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/private/tmp/awscurl-20230505-36434-1h15nfi/awscurl-0.28/setup.py", line 6, in <module>
        with open("requirements.txt", "r", encoding="utf-8") as f:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    error: subprocess-exited-with-error
```
It appears the release on PyPI, which we build from, is missing the requirements.txt file. This appears to be causing the failure.

Relates to https://github.com/Homebrew/homebrew-core/pull/130272

**Comment by chenrui333** [comment]
Seems working fine now with 0.29 release. Thanks!

**Comment by okigan** [comment]
Issue resolved
