### ISSUE TITLE
latest docker images after v0.29 failing on AMD64 

### ISSUE THREAD

**Issue by preetmyob** [okigan/awscurl#188]
@okigan Just wanted to give a head up. We've been using the older (previous latest v0.29) and it's been working fine. However we have been getting errors with every docker version over this one. 

These are the errors with "latest and v0.30" images
```
2023-10-18T21:50:36Z] Unable to find image 'okigan/awscurl:latest' locally
[2023-10-18T21:50:38Z] latest: Pulling from okigan/awscurl
96526aa774ef: Pull complete
9875af95546d: Pull complete
69babf7e971f: Pull complete
ba93e141e36c: Pull complete
f0588e5d3d11: Pull complete
026df7a0cea5: Pull complete
Digest: sha256:3b0d68b9e125f7c868de88aeab064dfa12fdbafffec1c6b7cf9cba510744fad3
[2023-10-18T21:50:42Z] Status: Downloaded newer image for okigan/awscurl:latest
[2023-10-18T21:50:44Z] Traceback (most recent call last):
[2023-10-18T21:50:44Z]   File "/app/python-packages/bin/awscurl", line 8, in <module>
[2023-10-18T21:50:44Z]     sys.exit(main())
[2023-10-18T21:50:44Z]              ^^^^^^
[2023-10-18T21:50:44Z]   File "/app/python-packages/awscurl/awscurl.py", line 544, in main
[2023-10-18T21:50:44Z]     inner_main(sys.argv[1:])
[2023-10-18T21:50:44Z]   File "/app/python-packages/awscurl/awscurl.py", line 512, in inner_main
[2023-10-18T21:50:44Z]     raise ValueError('No access key is available')
[2023-10-18T21:50:44Z] ValueError: No access key is available
```

This was on an amd64 platform, Amazon Linux 2 as the base OS

I think it might be related to the release of the `linux/arm64 images` 

reverting to v0.29 has resolved this issue.  

the command line: 

```
docker run --rm -ti -v "$HOME/.aws:/root/.aws" -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SECURITY_TOKEN -e AWS_PROFILE -e AWS_REGION okigan/awscurl:latest  "${api_url_base}/api/rxxxxx"

```

get OS Info

```
 NAME="Amazon Linux"
 VERSION="2"
 ID="amzn"
 ID_LIKE="centos rhel fedora"
 VERSION_ID="2"
 PRETTY_NAME="Amazon Linux 2"
 ANSI_COLOR="0;33"
 CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
 HOME_URL="https://amazonlinux.com/"
 SUPPORT_END="2025-06-30"
    Static hostname: ip-xx-xx-0-219.ap-southeast-2.compute.internal
          Icon name: computer-vm
            Chassis: vm
         Machine ID: ec235a926bcc95733a60060de1c05cf7
            Boot ID: f5c37107a79b4982b9775bf22933bcbe
     Virtualization: amazon
   Operating System: Amazon Linux 2
        CPE OS Name: cpe:2.3:o:amazon:amazon_linux:2
             Kernel: Linux 4.14.326-245.539.amzn2.x86_64
       Architecture: x86-64
 4.14.326-245.539.amzn2.x86_64
```

**Comment by okigan** [comment]
Thanks for reporting. What’s the command parameters you use to run it? On Oct 19, 2023, at 5:14 PM, Preet Sangha (MYOB) ***@***.***> wrote:﻿
@okigan Just wanted to give a head up. We've been using the older (previous latest v0.29) and it's been working fine. However we have been getting errors with very docker version over this one.
These are the errors with "latest and v0.30" images
2023-10-18T21:50:36Z] Unable to find image 'okigan/awscurl:latest' locally
[2023-10-18T21:50:38Z] latest: Pulling from okigan/awscurl
96526aa774ef: Pull complete
9875af95546d: Pull complete
69babf7e971f: Pull complete
ba93e141e36c: Pull complete
f0588e5d3d11: Pull complete
026df7a0cea5: Pull complete
Digest: sha256:3b0d68b9e125f7c868de88aeab064dfa12fdbafffec1c6b7cf9cba510744fad3
[2023-10-18T21:50:42Z] Status: Downloaded newer image for okigan/awscurl:latest
[2023-10-18T21:50:44Z] Traceback (most recent call last):
[2023-10-18T21:50:44Z]   File "/app/python-packages/bin/awscurl", line 8, in <module>
[2023-10-18T21:50:44Z]     sys.exit(main())
[2023-10-18T21:50:44Z]              ^^^^^^
[2023-10-18T21:50:44Z]   File "/app/python-packages/awscurl/awscurl.py", line 544, in main
[2023-10-18T21:50:44Z]     inner_main(sys.argv[1:])
[2023-10-18T21:50:44Z]   File "/app/python-packages/awscurl/awscurl.py", line 512, in inner_main
[2023-10-18T21:50:44Z]     raise ValueError('No access key is available')
[2023-10-18T21:50:44Z] ValueError: No access key is available

This was on an amd64 platform.
I think it might be related to the release of the linux/arm64 images

**Comment by preetmyob** [comment]
Hi @okigan,

our command is:

```
docker run --rm -ti -v "$HOME/.aws:/root/.aws" -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SECURITY_TOKEN -e AWS_PROFILE -e AWS_REGION okigan/awscurl:latest  "${api_url_base}/api/rxxxxx"
```

where `"${api_url_base}/api/rxxxxx"` is the url

**Comment by okigan** [comment]
@preetmyob please confirm if latest release resolve the issue

**Comment by preetmyob** [comment]
> @preetmyob please confirm if latest release resolve the issue

Hey there @okigan 

Yes Latest (v0.32) does indeed fix the problem. Thank you for your responsiveness in getting this fixed for us.

**Comment by okigan** [comment]
👍
