### ISSUE TITLE
syntax error in setup.py reported

### ISSUE THREAD

**Issue by b-yond** [okigan/awscurl#31]
Running setup.py install for awscurl
    SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/awscurl/awscurl.py', 322, 23, '    headers = {k: v for (k, v) in map(lambda s: s.split(": "), args.header)}\n'))

**Comment by okigan** [comment]
I don’t python 2.6 is a supported target, have u tried newer version?

**Comment by b-yond** [comment]
Thanks for the quick response. I managed to install w pip. 
Now getting this...

host [~] # awscurl --service s3 https://obfuscated-bucket-name.s3.amazonaws.com
Traceback (most recent call last):
  File "/usr/bin/awscurl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 551, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2165, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.5 has no such extra feature 'secure'

**Comment by okigan** [comment]
You are still running it on python 2.6, see paths in the error message: "/usr/lib/python2.6”...

**Comment by okigan** [comment]
See supported/test python versions: https://github.com/okigan/awscurl/blob/master/.travis.yml

**Comment by b-yond** [comment]
Thanks for the versions. I'm using these versions with up-to-date systems: 
CentOS 6.9 uses Python 2.6 as latest. 
CentOS 7 uses 2.7 as latest
Amazon Linux uses Python 2.7

I'm still getting this error on Python 2.7. Thanks for any help you can provide.

[ec2-user@ip-x-y-z-z ~]$ awscurl
Traceback (most recent call last):
  File "/usr/local/bin/awscurl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 866, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2590, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: urllib3 1.8.2 has no such extra feature 'secure'

**Comment by okigan** [comment]
@b-yond please update the issue by Jan 26 or moving it closed due to inactivity.

**Comment by anthonyagresta** [comment]
@b-yond I was able to install it successfully on Amazon Linux by doing the following first:
`sudo pip install urllib3[secure] --upgrade`
and then
`sudo pip install awscurl`

**Comment by okigan** [comment]
@b-yond @anthonyagresta any suggestions how to get 'sudo pip install urllib3[secure] --upgrade' equivalent into setup.py ?

**Comment by okigan** [comment]
closing due to inactivity.
