### ISSUE TITLE
requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you'll have urllib3 1.24 which is incompatible.

### ISSUE THREAD

**Issue by jmhummel** [okigan/awscurl#50]
Please update `setup.py` to install `urllib3<1.24,>=1.21.1`, as it currently pulls in 1.24 and throws the following error:
```Traceback (most recent call last):
  File "/usr/local/bin/awscurl", line 7, in <module>
    from awscurl.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/awscurl/__main__.py", line 6, in <module>
    from .awscurl import main
  File "/usr/local/lib/python2.7/dist-packages/awscurl/awscurl.py", line 14, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/local/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/local/lib/python2.7/dist-packages/requests/compat.py", line 48, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

**Comment by okigan** [comment]
PR merged - closing issue.
